name: Deploy to SAE

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow.
env:
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.sha }}

permissions:
  contents: read


jobs:
  stop-other-jobs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Stop other same workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Stop all waiting jobs about this workflow file
        run: |
          gh run list --workflow alibabacloud.yml --status waiting --json databaseId --jq '.[] | .databaseId' | while read -r id; do gh run cancel "$id"; done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: stop-other-jobs
    name: Deploy to Alibaba Cloud SAE    
    environment: deployment
    runs-on: ubuntu-latest
    # need after the job 'build' in workflow 'docker-publish.yml'    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1.1 Install Aliyun CLI
    - name: Install Aliyun CLI
      uses: aliyun/setup-aliyun-cli-action@v1

    # 1.2 Setup Aliyun credentials
    - name: Setup Aliyun credentials
      run: |
        aliyun configure set --access-key-id ${{ secrets.ACCESS_KEY_ID }}   --access-key-secret ${{ secrets.ACCESS_KEY_SECRET }}   --region ${{ vars.REGION_ID }}   --profile AkProfile   --mode AK   --language en

    # 2.1 Stop the existing application
    # should ignore the error because the application may not be running
    - name: Stop the existing application
      run: |
        aliyun sae PUT /pop/v1/sam/app/stopApplication --AppId '${{ vars.APP_ID }}' --header "Content-Type=application/json;" --body "{}"
      continue-on-error: true

    # 2.2 Sleep for 20 seconds
    - name: Sleep for 20 seconds
      run: sleep 20

    # 2.3 Deploy the new version
    - name: Deploy the new version
      run: |
        aliyun sae PUT /pop/v1/sam/app/startApplication --AppId '${{ vars.APP_ID }}' --header "Content-Type=application/json;" --body "{}"
  build-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    name: Build Failure
    runs-on: ubuntu-latest
    steps:
      - name: Notify Build Failure
        run: echo "Build failed. Please check the logs."

    